### ISSUE TITLE
Throttling / queueing of frames on LCC CAN

### ISSUE THREAD

**Issue by balazsracz** [rm5248/TrainUtils#1]
The API of the write callback on LCC is defined as "fire and forget":
https://github.com/rm5248/TrainUtils/blob/master/LCC/examples/simple-node/simple-node.ino#L28C1-L28C1

This API assumes that any time that the stack decides to call this function, the bus is free. This is not a valid assumption. The LCC stack must be prepared for the bus being busy and stop generating frames until the previously generated frames were transmitted to the bus.

It is important that when the writes to the bus are throttled, the stack must still read and process the incoming traffic. Therefore it is not an OK solution to pause the stack until the output frame was transmitted. It is also true that the new incoming traffic might generate output data, which might seem like a contradiction.
There are four priority bands in OpenLCB, and it is designed such that a request of priority X will generate a response of priority X-1, therefore even in the presence of a fully loaded bus, the responses that are generated will go out.

The way LibLCC is written today, it will lose messages when the output buffer in the CAN controller is occupied. This will cause problems that are hard to recognize and reproduce. The assumption of LCC is that all messages are delivered.

**Comment by rm5248** [comment]
> This API assumes that any time that the stack decides to call this function, the bus is free.

The intention is that the API assumes that the callback will send it out to the bus at some point.  If the user needs to queue up the data because a buffer is full, they should do that.  If you're using Linux, the kernel will handle the queuing up of the data(up to a certain point, of course).

It is a valid point that there is no way for the callback to indicate that the buffer is full at the moment.  The way the [ACAN2515 library works](https://github.com/pierremolinaro/acan2515/blob/5ae235d374b1bc15616120660ce0fe6d71bb636f/src/ACAN2515.cpp#L931) is that if the MCP2515 does not have space in its transmit buffer, it will copy it to a local buffer and then send it out once there is a free transmit buffer on the 2515.  The example does set the transmit buffer to be [8 deep,](https://github.com/rm5248/TrainUtils/blob/e488a1002a76817e50eadbc5fcbd572372b55a34/LCC/examples/simple-node/simple-node.ino#L101) giving us a total of 9 CAN messages that we can queue up.  

From my reading of the spec, the largest number of frames that we can reasonably generate at a single time would be 8, as that would be a full datagram transfer of 64 bytes.  So there is a possibility that we can have an overrun, but given the limited memory on the Uno there is a tradeoff of how many frames we can buffer vs. being able to ensure that we send out everything.
